# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainLayout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1008, 667)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.redraw = QtWidgets.QPushButton(self.centralwidget)
        self.redraw.setMinimumSize(QtCore.QSize(50, 20))
        self.redraw.setMaximumSize(QtCore.QSize(50, 20))
        self.redraw.setObjectName("redraw")
        self.horizontalLayout.addWidget(self.redraw)
        self.redrawSpectrogramUI = QtWidgets.QPushButton(self.centralwidget)
        self.redrawSpectrogramUI.setMinimumSize(QtCore.QSize(50, 20))
        self.redrawSpectrogramUI.setMaximumSize(QtCore.QSize(50, 20))
        self.redrawSpectrogramUI.setObjectName("redrawSpectrogramUI")
        self.horizontalLayout.addWidget(self.redrawSpectrogramUI)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(298, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.shot = QtWidgets.QLineEdit(self.centralwidget)
        self.shot.setMinimumSize(QtCore.QSize(80, 0))
        self.shot.setMaximumSize(QtCore.QSize(100, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.shot.setFont(font)
        self.shot.setPlaceholderText("")
        self.shot.setObjectName("shot")
        self.horizontalLayout.addWidget(self.shot)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.resampling = QtWidgets.QLineEdit(self.centralwidget)
        self.resampling.setMinimumSize(QtCore.QSize(80, 0))
        self.resampling.setMaximumSize(QtCore.QSize(100, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.resampling.setFont(font)
        self.resampling.setPlaceholderText("")
        self.resampling.setObjectName("resampling")
        self.horizontalLayout.addWidget(self.resampling)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.samplingRate_kHz = QtWidgets.QLineEdit(self.centralwidget)
        self.samplingRate_kHz.setMinimumSize(QtCore.QSize(80, 0))
        self.samplingRate_kHz.setMaximumSize(QtCore.QSize(100, 15))
        self.samplingRate_kHz.setObjectName("samplingRate_kHz")
        self.horizontalLayout.addWidget(self.samplingRate_kHz)
        self.SGFilt = QtWidgets.QCheckBox(self.centralwidget)
        self.SGFilt.setTristate(False)
        self.SGFilt.setObjectName("SGFilt")
        self.horizontalLayout.addWidget(self.SGFilt)
        self.subtrFilt = QtWidgets.QCheckBox(self.centralwidget)
        self.subtrFilt.setObjectName("subtrFilt")
        self.horizontalLayout.addWidget(self.subtrFilt)
        self.replaceWithSGFilt = QtWidgets.QCheckBox(self.centralwidget)
        self.replaceWithSGFilt.setMinimumSize(QtCore.QSize(95, 0))
        self.replaceWithSGFilt.setMaximumSize(QtCore.QSize(95, 16777215))
        self.replaceWithSGFilt.setTristate(False)
        self.replaceWithSGFilt.setObjectName("replaceWithSGFilt")
        self.horizontalLayout.addWidget(self.replaceWithSGFilt)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.winLength = QtWidgets.QLineEdit(self.centralwidget)
        self.winLength.setMinimumSize(QtCore.QSize(50, 0))
        self.winLength.setMaximumSize(QtCore.QSize(80, 15))
        self.winLength.setObjectName("winLength")
        self.horizontalLayout.addWidget(self.winLength)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.polyOrder = QtWidgets.QLineEdit(self.centralwidget)
        self.polyOrder.setMinimumSize(QtCore.QSize(50, 15))
        self.polyOrder.setMaximumSize(QtCore.QSize(80, 15))
        self.polyOrder.setObjectName("polyOrder")
        self.horizontalLayout.addWidget(self.polyOrder)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.plot = PlotWidget(self.centralwidget)
        self.plot.setBaseSize(QtCore.QSize(0, 0))
        self.plot.setObjectName("plot")
        self.verticalLayout.addWidget(self.plot)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1008, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_csv = QtWidgets.QAction(MainWindow)
        self.actionOpen_csv.setObjectName("actionOpen_csv")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExport_to_csv = QtWidgets.QAction(MainWindow)
        self.actionExport_to_csv.setObjectName("actionExport_to_csv")
        self.actionDrawPlotsFromCsv = QtWidgets.QAction(MainWindow)
        self.actionDrawPlotsFromCsv.setObjectName("actionDrawPlotsFromCsv")
        self.actionOpen_mdsplus_QXT = QtWidgets.QAction(MainWindow)
        self.actionOpen_mdsplus_QXT.setObjectName("actionOpen_mdsplus_QXT")
        self.actionDrawPlotsFromMdsplus = QtWidgets.QAction(MainWindow)
        self.actionDrawPlotsFromMdsplus.setObjectName("actionDrawPlotsFromMdsplus")
        self.actionExport_time_to_separate_file = QtWidgets.QAction(MainWindow)
        self.actionExport_time_to_separate_file.setObjectName("actionExport_time_to_separate_file")
        self.actionOpen_mdsplus_QOC = QtWidgets.QAction(MainWindow)
        self.actionOpen_mdsplus_QOC.setObjectName("actionOpen_mdsplus_QOC")
        self.menuFile.addAction(self.actionOpen_mdsplus_QXT)
        self.menuFile.addAction(self.actionOpen_mdsplus_QOC)
        self.menuFile.addAction(self.actionDrawPlotsFromMdsplus)
        self.menuFile.addAction(self.actionExport_time_to_separate_file)
        self.menuFile.addAction(self.actionExport_to_csv)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_csv)
        self.menuFile.addAction(self.actionDrawPlotsFromCsv)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClear)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.redraw.setText(_translate("MainWindow", "draw"))
        self.redrawSpectrogramUI.setText(_translate("MainWindow", "spectr"))
        self.label.setText(_translate("MainWindow", "shot"))
        self.shot.setToolTip(_translate("MainWindow", "<html><head/><body><p>shot number</p></body></html>"))
        self.shot.setText(_translate("MainWindow", "180816020"))
        self.label_2.setText(_translate("MainWindow", "resampling"))
        self.resampling.setToolTip(_translate("MainWindow", "<html><head/><body><p>set &quot;1&quot; for no resampling</p></body></html>"))
        self.resampling.setText(_translate("MainWindow", "1"))
        self.label_3.setText(_translate("MainWindow", "samplingRate_kHz"))
        self.samplingRate_kHz.setText(_translate("MainWindow", "1000"))
        self.SGFilt.setText(_translate("MainWindow", "showSGF"))
        self.subtrFilt.setText(_translate("MainWindow", "-SGF"))
        self.replaceWithSGFilt.setText(_translate("MainWindow", "=SGF"))
        self.label_4.setText(_translate("MainWindow", "winLength"))
        self.winLength.setToolTip(_translate("MainWindow", "must be odd!"))
        self.winLength.setText(_translate("MainWindow", "1001"))
        self.label_5.setText(_translate("MainWindow", "polyOrder"))
        self.polyOrder.setText(_translate("MainWindow", "0"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_csv.setText(_translate("MainWindow", "Open_csv"))
        self.actionClear.setText(_translate("MainWindow", "ClearPlots"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "about"))
        self.actionExport_to_csv.setText(_translate("MainWindow", "Export to csv"))
        self.actionDrawPlotsFromCsv.setText(_translate("MainWindow", "DrawPlotsFromCsv"))
        self.actionOpen_mdsplus_QXT.setText(_translate("MainWindow", "Open_mdsplus_QXT"))
        self.actionDrawPlotsFromMdsplus.setText(_translate("MainWindow", "DrawPlotsFromMdsplus"))
        self.actionExport_time_to_separate_file.setText(_translate("MainWindow", "Export time to separate file"))
        self.actionOpen_mdsplus_QOC.setText(_translate("MainWindow", "Open_mdsplus_QOC"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

