# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectrogramLayout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1052, 587)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.redrawSpectrogramBtn = QtWidgets.QPushButton(self.centralwidget)
        self.redrawSpectrogramBtn.setMinimumSize(QtCore.QSize(50, 20))
        self.redrawSpectrogramBtn.setMaximumSize(QtCore.QSize(50, 20))
        self.redrawSpectrogramBtn.setObjectName("redrawSpectrogramBtn")
        self.horizontalLayout.addWidget(self.redrawSpectrogramBtn)
        self.resetParams_ui = QtWidgets.QPushButton(self.centralwidget)
        self.resetParams_ui.setMinimumSize(QtCore.QSize(50, 20))
        self.resetParams_ui.setMaximumSize(QtCore.QSize(50, 20))
        self.resetParams_ui.setObjectName("resetParams_ui")
        self.horizontalLayout.addWidget(self.resetParams_ui)
        self.scaleLinLogSqrt = QtWidgets.QComboBox(self.centralwidget)
        self.scaleLinLogSqrt.setMinimumSize(QtCore.QSize(50, 20))
        self.scaleLinLogSqrt.setMaximumSize(QtCore.QSize(50, 20))
        self.scaleLinLogSqrt.setObjectName("scaleLinLogSqrt")
        self.scaleLinLogSqrt.addItem("")
        self.scaleLinLogSqrt.addItem("")
        self.scaleLinLogSqrt.addItem("")
        self.horizontalLayout.addWidget(self.scaleLinLogSqrt)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(50, 15))
        self.label.setMaximumSize(QtCore.QSize(20, 15))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.nfft_ui = QtWidgets.QLineEdit(self.centralwidget)
        self.nfft_ui.setMinimumSize(QtCore.QSize(50, 15))
        self.nfft_ui.setMaximumSize(QtCore.QSize(50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.nfft_ui.setFont(font)
        self.nfft_ui.setPlaceholderText("")
        self.nfft_ui.setObjectName("nfft_ui")
        self.horizontalLayout.addWidget(self.nfft_ui)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(50, 15))
        self.label_2.setMaximumSize(QtCore.QSize(50, 15))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.fs_kHz_ui = QtWidgets.QLineEdit(self.centralwidget)
        self.fs_kHz_ui.setMinimumSize(QtCore.QSize(50, 15))
        self.fs_kHz_ui.setMaximumSize(QtCore.QSize(50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fs_kHz_ui.setFont(font)
        self.fs_kHz_ui.setPlaceholderText("")
        self.fs_kHz_ui.setObjectName("fs_kHz_ui")
        self.horizontalLayout.addWidget(self.fs_kHz_ui)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(50, 15))
        self.label_3.setMaximumSize(QtCore.QSize(20, 15))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.window_ui = QtWidgets.QLineEdit(self.centralwidget)
        self.window_ui.setMinimumSize(QtCore.QSize(80, 15))
        self.window_ui.setMaximumSize(QtCore.QSize(80, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.window_ui.setFont(font)
        self.window_ui.setPlaceholderText("")
        self.window_ui.setObjectName("window_ui")
        self.horizontalLayout.addWidget(self.window_ui)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(50, 15))
        self.label_4.setMaximumSize(QtCore.QSize(20, 15))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.nperseg_ui = QtWidgets.QLineEdit(self.centralwidget)
        self.nperseg_ui.setMinimumSize(QtCore.QSize(50, 15))
        self.nperseg_ui.setMaximumSize(QtCore.QSize(50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.nperseg_ui.setFont(font)
        self.nperseg_ui.setPlaceholderText("")
        self.nperseg_ui.setObjectName("nperseg_ui")
        self.horizontalLayout.addWidget(self.nperseg_ui)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(50, 15))
        self.label_5.setMaximumSize(QtCore.QSize(20, 15))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.noverlap_ui = QtWidgets.QLineEdit(self.centralwidget)
        self.noverlap_ui.setMinimumSize(QtCore.QSize(50, 15))
        self.noverlap_ui.setMaximumSize(QtCore.QSize(50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.noverlap_ui.setFont(font)
        self.noverlap_ui.setPlaceholderText("")
        self.noverlap_ui.setObjectName("noverlap_ui")
        self.horizontalLayout.addWidget(self.noverlap_ui)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(50, 15))
        self.label_6.setMaximumSize(QtCore.QSize(20, 15))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.detrend_ui = QtWidgets.QLineEdit(self.centralwidget)
        self.detrend_ui.setMinimumSize(QtCore.QSize(50, 15))
        self.detrend_ui.setMaximumSize(QtCore.QSize(50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.detrend_ui.setFont(font)
        self.detrend_ui.setPlaceholderText("")
        self.detrend_ui.setObjectName("detrend_ui")
        self.horizontalLayout.addWidget(self.detrend_ui)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMinimumSize(QtCore.QSize(50, 15))
        self.label_7.setMaximumSize(QtCore.QSize(20, 15))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.scaling_ui = QtWidgets.QLineEdit(self.centralwidget)
        self.scaling_ui.setMinimumSize(QtCore.QSize(50, 15))
        self.scaling_ui.setMaximumSize(QtCore.QSize(50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.scaling_ui.setFont(font)
        self.scaling_ui.setPlaceholderText("")
        self.scaling_ui.setObjectName("scaling_ui")
        self.horizontalLayout.addWidget(self.scaling_ui)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMinimumSize(QtCore.QSize(50, 15))
        self.label_8.setMaximumSize(QtCore.QSize(20, 15))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.mode_ui = QtWidgets.QLineEdit(self.centralwidget)
        self.mode_ui.setMinimumSize(QtCore.QSize(50, 15))
        self.mode_ui.setMaximumSize(QtCore.QSize(50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mode_ui.setFont(font)
        self.mode_ui.setPlaceholderText("")
        self.mode_ui.setObjectName("mode_ui")
        self.horizontalLayout.addWidget(self.mode_ui)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.spectrogram_UI = GraphicsLayoutWidget(self.centralwidget)
        self.spectrogram_UI.setEnabled(True)
        self.spectrogram_UI.setBaseSize(QtCore.QSize(0, 0))
        self.spectrogram_UI.setObjectName("spectrogram_UI")
        self.verticalLayout.addWidget(self.spectrogram_UI)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1052, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_csv = QtWidgets.QAction(MainWindow)
        self.actionOpen_csv.setObjectName("actionOpen_csv")
        self.actionGenerateTestData = QtWidgets.QAction(MainWindow)
        self.actionGenerateTestData.setObjectName("actionGenerateTestData")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExport_to_csv = QtWidgets.QAction(MainWindow)
        self.actionExport_to_csv.setObjectName("actionExport_to_csv")
        self.actionDrawPlotsFromCsv = QtWidgets.QAction(MainWindow)
        self.actionDrawPlotsFromCsv.setObjectName("actionDrawPlotsFromCsv")
        self.actionOpen_mdsplus_QXT = QtWidgets.QAction(MainWindow)
        self.actionOpen_mdsplus_QXT.setObjectName("actionOpen_mdsplus_QXT")
        self.actionDrawPlotsFromMdsplus = QtWidgets.QAction(MainWindow)
        self.actionDrawPlotsFromMdsplus.setObjectName("actionDrawPlotsFromMdsplus")
        self.actionExport_time_to_separate_file = QtWidgets.QAction(MainWindow)
        self.actionExport_time_to_separate_file.setObjectName("actionExport_time_to_separate_file")
        self.actionOpen_mdsplus_QOC = QtWidgets.QAction(MainWindow)
        self.actionOpen_mdsplus_QOC.setObjectName("actionOpen_mdsplus_QOC")
        self.actionClearAll = QtWidgets.QAction(MainWindow)
        self.actionClearAll.setObjectName("actionClearAll")
        self.menuFile.addAction(self.actionGenerateTestData)
        self.menuFile.addAction(self.actionClearAll)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.redrawSpectrogramBtn.setText(_translate("MainWindow", "draw"))
        self.resetParams_ui.setText(_translate("MainWindow", "reset"))
        self.scaleLinLogSqrt.setItemText(0, _translate("MainWindow", "linear"))
        self.scaleLinLogSqrt.setItemText(1, _translate("MainWindow", "log10"))
        self.scaleLinLogSqrt.setItemText(2, _translate("MainWindow", "sqrt"))
        self.label.setText(_translate("MainWindow", "nfft"))
        self.nfft_ui.setText(_translate("MainWindow", "256"))
        self.label_2.setText(_translate("MainWindow", "fs,kHz"))
        self.fs_kHz_ui.setText(_translate("MainWindow", "1000"))
        self.label_3.setText(_translate("MainWindow", "window"))
        self.window_ui.setText(_translate("MainWindow", "hamming"))
        self.label_4.setText(_translate("MainWindow", "nperseg"))
        self.nperseg_ui.setText(_translate("MainWindow", "256"))
        self.label_5.setText(_translate("MainWindow", "noverlap"))
        self.noverlap_ui.setText(_translate("MainWindow", "32"))
        self.label_6.setText(_translate("MainWindow", "detrend"))
        self.detrend_ui.setText(_translate("MainWindow", "constant"))
        self.label_7.setText(_translate("MainWindow", "scaling"))
        self.scaling_ui.setText(_translate("MainWindow", "density"))
        self.label_8.setText(_translate("MainWindow", "mode"))
        self.mode_ui.setText(_translate("MainWindow", "psd"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_csv.setText(_translate("MainWindow", "Open_csv"))
        self.actionGenerateTestData.setText(_translate("MainWindow", "generateTestData"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "about"))
        self.actionExport_to_csv.setText(_translate("MainWindow", "Export to csv"))
        self.actionDrawPlotsFromCsv.setText(_translate("MainWindow", "DrawPlotsFromCsv"))
        self.actionOpen_mdsplus_QXT.setText(_translate("MainWindow", "Open_mdsplus_QXT"))
        self.actionDrawPlotsFromMdsplus.setText(_translate("MainWindow", "DrawPlotsFromMdsplus"))
        self.actionExport_time_to_separate_file.setText(_translate("MainWindow", "Export time to separate file"))
        self.actionOpen_mdsplus_QOC.setText(_translate("MainWindow", "Open_mdsplus_QOC"))
        self.actionClearAll.setText(_translate("MainWindow", "ClearAll"))

from pyqtgraph import GraphicsLayoutWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

