# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectrogramLayout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Spectrogram(object):
    def setupUi(self, Spectrogram):
        Spectrogram.setObjectName("Spectrogram")
        Spectrogram.resize(1314, 587)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Spectrogram.sizePolicy().hasHeightForWidth())
        Spectrogram.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(Spectrogram)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.redrawSpectrogramBtn = QtWidgets.QPushButton(self.centralwidget)
        self.redrawSpectrogramBtn.setMinimumSize(QtCore.QSize(50, 20))
        self.redrawSpectrogramBtn.setMaximumSize(QtCore.QSize(50, 20))
        self.redrawSpectrogramBtn.setObjectName("redrawSpectrogramBtn")
        self.gridLayout.addWidget(self.redrawSpectrogramBtn, 0, 0, 1, 1)
        self.settings_btn = QtWidgets.QPushButton(self.centralwidget)
        self.settings_btn.setMinimumSize(QtCore.QSize(55, 20))
        self.settings_btn.setMaximumSize(QtCore.QSize(55, 20))
        self.settings_btn.setObjectName("settings_btn")
        self.gridLayout.addWidget(self.settings_btn, 0, 1, 1, 1)
        self.mouseXY_UI = QtWidgets.QLabel(self.centralwidget)
        self.mouseXY_UI.setObjectName("mouseXY_UI")
        self.gridLayout.addWidget(self.mouseXY_UI, 0, 2, 1, 1)
        self.horizontalLayout_spectr = QtWidgets.QHBoxLayout()
        self.horizontalLayout_spectr.setObjectName("horizontalLayout_spectr")
        self.spectrogram_UI = GraphicsLayoutWidget(self.centralwidget)
        self.spectrogram_UI.setEnabled(True)
        self.spectrogram_UI.setBaseSize(QtCore.QSize(0, 0))
        self.spectrogram_UI.setObjectName("spectrogram_UI")
        self.horizontalLayout_spectr.addWidget(self.spectrogram_UI)
        self.gridLayout.addLayout(self.horizontalLayout_spectr, 1, 0, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        Spectrogram.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Spectrogram)
        self.statusbar.setObjectName("statusbar")
        Spectrogram.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(Spectrogram)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1314, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        Spectrogram.setMenuBar(self.menubar)
        self.actionOpen_csv = QtWidgets.QAction(Spectrogram)
        self.actionOpen_csv.setObjectName("actionOpen_csv")
        self.actionGenerateTestData = QtWidgets.QAction(Spectrogram)
        self.actionGenerateTestData.setObjectName("actionGenerateTestData")
        self.actionExit = QtWidgets.QAction(Spectrogram)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(Spectrogram)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExport_to_csv = QtWidgets.QAction(Spectrogram)
        self.actionExport_to_csv.setObjectName("actionExport_to_csv")
        self.actionDrawPlotsFromCsv = QtWidgets.QAction(Spectrogram)
        self.actionDrawPlotsFromCsv.setObjectName("actionDrawPlotsFromCsv")
        self.actionOpen_mdsplus_QXT = QtWidgets.QAction(Spectrogram)
        self.actionOpen_mdsplus_QXT.setObjectName("actionOpen_mdsplus_QXT")
        self.actionDrawPlotsFromMdsplus = QtWidgets.QAction(Spectrogram)
        self.actionDrawPlotsFromMdsplus.setObjectName("actionDrawPlotsFromMdsplus")
        self.actionExport_time_to_separate_file = QtWidgets.QAction(Spectrogram)
        self.actionExport_time_to_separate_file.setObjectName("actionExport_time_to_separate_file")
        self.actionOpen_mdsplus_QOC = QtWidgets.QAction(Spectrogram)
        self.actionOpen_mdsplus_QOC.setObjectName("actionOpen_mdsplus_QOC")
        self.actionClearAll = QtWidgets.QAction(Spectrogram)
        self.actionClearAll.setEnabled(True)
        self.actionClearAll.setObjectName("actionClearAll")
        self.actionOpen_mdsplus = QtWidgets.QAction(Spectrogram)
        self.actionOpen_mdsplus.setObjectName("actionOpen_mdsplus")
        self.menuFile.addAction(self.actionGenerateTestData)
        self.menuFile.addAction(self.actionOpen_mdsplus)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClearAll)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Spectrogram)
        QtCore.QMetaObject.connectSlotsByName(Spectrogram)

    def retranslateUi(self, Spectrogram):
        _translate = QtCore.QCoreApplication.translate
        Spectrogram.setWindowTitle(_translate("Spectrogram", "Spectrogram"))
        self.redrawSpectrogramBtn.setToolTip(_translate("Spectrogram", "\'Shift\'+\'D\'"))
        self.redrawSpectrogramBtn.setText(_translate("Spectrogram", "draw"))
        self.settings_btn.setToolTip(_translate("Spectrogram", "\'Shift\'+\'S\'"))
        self.settings_btn.setText(_translate("Spectrogram", "settings"))
        self.mouseXY_UI.setText(_translate("Spectrogram", "mouse X, Y"))
        self.menuFile.setTitle(_translate("Spectrogram", "File"))
        self.actionOpen_csv.setText(_translate("Spectrogram", "Open_csv"))
        self.actionGenerateTestData.setText(_translate("Spectrogram", "Generate Test Data"))
        self.actionExit.setText(_translate("Spectrogram", "Exit"))
        self.actionAbout.setText(_translate("Spectrogram", "about"))
        self.actionExport_to_csv.setText(_translate("Spectrogram", "Export to csv"))
        self.actionDrawPlotsFromCsv.setText(_translate("Spectrogram", "DrawPlotsFromCsv"))
        self.actionOpen_mdsplus_QXT.setText(_translate("Spectrogram", "Open_mdsplus_QXT"))
        self.actionDrawPlotsFromMdsplus.setText(_translate("Spectrogram", "DrawPlotsFromMdsplus"))
        self.actionExport_time_to_separate_file.setText(_translate("Spectrogram", "Export time to separate file"))
        self.actionOpen_mdsplus_QOC.setText(_translate("Spectrogram", "Open_mdsplus_QOC"))
        self.actionClearAll.setText(_translate("Spectrogram", "ClearAll"))
        self.actionOpen_mdsplus.setText(_translate("Spectrogram", "Open mdsplus"))

from pyqtgraph import GraphicsLayoutWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Spectrogram = QtWidgets.QMainWindow()
    ui = Ui_Spectrogram()
    ui.setupUi(Spectrogram)
    Spectrogram.show()
    sys.exit(app.exec_())

