# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectrogramLayout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1314, 587)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.redrawSpectrogramBtn = QtWidgets.QPushButton(self.centralwidget)
        self.redrawSpectrogramBtn.setMinimumSize(QtCore.QSize(50, 20))
        self.redrawSpectrogramBtn.setMaximumSize(QtCore.QSize(50, 20))
        self.redrawSpectrogramBtn.setObjectName("redrawSpectrogramBtn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.redrawSpectrogramBtn)
        self.settings_btn = QtWidgets.QPushButton(self.centralwidget)
        self.settings_btn.setMinimumSize(QtCore.QSize(55, 20))
        self.settings_btn.setMaximumSize(QtCore.QSize(55, 20))
        self.settings_btn.setObjectName("settings_btn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.settings_btn)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_spectr = QtWidgets.QHBoxLayout()
        self.horizontalLayout_spectr.setObjectName("horizontalLayout_spectr")
        self.spectrogram_UI = GraphicsLayoutWidget(self.centralwidget)
        self.spectrogram_UI.setEnabled(True)
        self.spectrogram_UI.setBaseSize(QtCore.QSize(0, 0))
        self.spectrogram_UI.setObjectName("spectrogram_UI")
        self.horizontalLayout_spectr.addWidget(self.spectrogram_UI)
        self.verticalLayout.addLayout(self.horizontalLayout_spectr)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1314, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_csv = QtWidgets.QAction(MainWindow)
        self.actionOpen_csv.setObjectName("actionOpen_csv")
        self.actionGenerateTestData = QtWidgets.QAction(MainWindow)
        self.actionGenerateTestData.setObjectName("actionGenerateTestData")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExport_to_csv = QtWidgets.QAction(MainWindow)
        self.actionExport_to_csv.setObjectName("actionExport_to_csv")
        self.actionDrawPlotsFromCsv = QtWidgets.QAction(MainWindow)
        self.actionDrawPlotsFromCsv.setObjectName("actionDrawPlotsFromCsv")
        self.actionOpen_mdsplus_QXT = QtWidgets.QAction(MainWindow)
        self.actionOpen_mdsplus_QXT.setObjectName("actionOpen_mdsplus_QXT")
        self.actionDrawPlotsFromMdsplus = QtWidgets.QAction(MainWindow)
        self.actionDrawPlotsFromMdsplus.setObjectName("actionDrawPlotsFromMdsplus")
        self.actionExport_time_to_separate_file = QtWidgets.QAction(MainWindow)
        self.actionExport_time_to_separate_file.setObjectName("actionExport_time_to_separate_file")
        self.actionOpen_mdsplus_QOC = QtWidgets.QAction(MainWindow)
        self.actionOpen_mdsplus_QOC.setObjectName("actionOpen_mdsplus_QOC")
        self.actionClearAll = QtWidgets.QAction(MainWindow)
        self.actionClearAll.setObjectName("actionClearAll")
        self.menuFile.addAction(self.actionGenerateTestData)
        self.menuFile.addAction(self.actionClearAll)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.redrawSpectrogramBtn.setText(_translate("MainWindow", "draw"))
        self.settings_btn.setText(_translate("MainWindow", "settings"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_csv.setText(_translate("MainWindow", "Open_csv"))
        self.actionGenerateTestData.setText(_translate("MainWindow", "generateTestData"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "about"))
        self.actionExport_to_csv.setText(_translate("MainWindow", "Export to csv"))
        self.actionDrawPlotsFromCsv.setText(_translate("MainWindow", "DrawPlotsFromCsv"))
        self.actionOpen_mdsplus_QXT.setText(_translate("MainWindow", "Open_mdsplus_QXT"))
        self.actionDrawPlotsFromMdsplus.setText(_translate("MainWindow", "DrawPlotsFromMdsplus"))
        self.actionExport_time_to_separate_file.setText(_translate("MainWindow", "Export time to separate file"))
        self.actionOpen_mdsplus_QOC.setText(_translate("MainWindow", "Open_mdsplus_QOC"))
        self.actionClearAll.setText(_translate("MainWindow", "ClearAll"))

from pyqtgraph import GraphicsLayoutWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

