# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectrogramSettingsLayout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_spectrogramSettingsWidget(object):
    def setupUi(self, spectrogramSettingsWidget):
        spectrogramSettingsWidget.setObjectName("spectrogramSettingsWidget")
        spectrogramSettingsWidget.resize(650, 240)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(spectrogramSettingsWidget.sizePolicy().hasHeightForWidth())
        spectrogramSettingsWidget.setSizePolicy(sizePolicy)
        spectrogramSettingsWidget.setMinimumSize(QtCore.QSize(650, 240))
        spectrogramSettingsWidget.setMaximumSize(QtCore.QSize(650, 240))
        self.layoutWidget = QtWidgets.QWidget(spectrogramSettingsWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 644, 223))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(130, 15))
        self.label_2.setMaximumSize(QtCore.QSize(130, 15))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(50, 15))
        self.label.setMaximumSize(QtCore.QSize(50, 15))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.nfft_ui = QtWidgets.QLineEdit(self.layoutWidget)
        self.nfft_ui.setMinimumSize(QtCore.QSize(60, 20))
        self.nfft_ui.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.nfft_ui.setFont(font)
        self.nfft_ui.setPlaceholderText("")
        self.nfft_ui.setObjectName("nfft_ui")
        self.gridLayout.addWidget(self.nfft_ui, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(50, 15))
        self.label_4.setMaximumSize(QtCore.QSize(50, 15))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.nperseg_ui = QtWidgets.QLineEdit(self.layoutWidget)
        self.nperseg_ui.setMinimumSize(QtCore.QSize(60, 20))
        self.nperseg_ui.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.nperseg_ui.setFont(font)
        self.nperseg_ui.setPlaceholderText("")
        self.nperseg_ui.setObjectName("nperseg_ui")
        self.gridLayout.addWidget(self.nperseg_ui, 0, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(50, 15))
        self.label_5.setMaximumSize(QtCore.QSize(50, 15))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 6, 1, 1, QtCore.Qt.AlignRight)
        self.noverlap_ui = QtWidgets.QLineEdit(self.layoutWidget)
        self.noverlap_ui.setMinimumSize(QtCore.QSize(60, 20))
        self.noverlap_ui.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.noverlap_ui.setFont(font)
        self.noverlap_ui.setPlaceholderText("")
        self.noverlap_ui.setObjectName("noverlap_ui")
        self.gridLayout.addWidget(self.noverlap_ui, 0, 7, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(50, 15))
        self.label_3.setMaximumSize(QtCore.QSize(50, 15))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.window_ui = QtWidgets.QLineEdit(self.layoutWidget)
        self.window_ui.setMinimumSize(QtCore.QSize(60, 20))
        self.window_ui.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.window_ui.setFont(font)
        self.window_ui.setPlaceholderText("")
        self.window_ui.setObjectName("window_ui")
        self.gridLayout.addWidget(self.window_ui, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(50, 15))
        self.label_6.setMaximumSize(QtCore.QSize(50, 15))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.detrend_ui = QtWidgets.QLineEdit(self.layoutWidget)
        self.detrend_ui.setMinimumSize(QtCore.QSize(60, 20))
        self.detrend_ui.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.detrend_ui.setFont(font)
        self.detrend_ui.setPlaceholderText("")
        self.detrend_ui.setObjectName("detrend_ui")
        self.gridLayout.addWidget(self.detrend_ui, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(50, 15))
        self.label_7.setMaximumSize(QtCore.QSize(50, 15))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 4, 1, 1)
        self.scaling_ui = QtWidgets.QLineEdit(self.layoutWidget)
        self.scaling_ui.setMinimumSize(QtCore.QSize(60, 20))
        self.scaling_ui.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.scaling_ui.setFont(font)
        self.scaling_ui.setPlaceholderText("")
        self.scaling_ui.setObjectName("scaling_ui")
        self.gridLayout.addWidget(self.scaling_ui, 1, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(50, 15))
        self.label_8.setMaximumSize(QtCore.QSize(50, 15))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 6, 1, 1, QtCore.Qt.AlignRight)
        self.mode_ui = QtWidgets.QLineEdit(self.layoutWidget)
        self.mode_ui.setMinimumSize(QtCore.QSize(60, 20))
        self.mode_ui.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mode_ui.setFont(font)
        self.mode_ui.setPlaceholderText("")
        self.mode_ui.setObjectName("mode_ui")
        self.gridLayout.addWidget(self.mode_ui, 1, 7, 1, 1)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 8)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.applyBandPass_ui = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.applyBandPass_ui.sizePolicy().hasHeightForWidth())
        self.applyBandPass_ui.setSizePolicy(sizePolicy)
        self.applyBandPass_ui.setMinimumSize(QtCore.QSize(60, 20))
        self.applyBandPass_ui.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.applyBandPass_ui.setText("")
        self.applyBandPass_ui.setTristate(False)
        self.applyBandPass_ui.setObjectName("applyBandPass_ui")
        self.gridLayout.addWidget(self.applyBandPass_ui, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setMinimumSize(QtCore.QSize(0, 15))
        self.label_10.setMaximumSize(QtCore.QSize(50, 15))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 2, 1, 1)
        self.bandpassLowcut_kHz_ui = QtWidgets.QLineEdit(self.layoutWidget)
        self.bandpassLowcut_kHz_ui.setMinimumSize(QtCore.QSize(60, 20))
        self.bandpassLowcut_kHz_ui.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.bandpassLowcut_kHz_ui.setFont(font)
        self.bandpassLowcut_kHz_ui.setPlaceholderText("")
        self.bandpassLowcut_kHz_ui.setObjectName("bandpassLowcut_kHz_ui")
        self.gridLayout.addWidget(self.bandpassLowcut_kHz_ui, 3, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setMinimumSize(QtCore.QSize(0, 15))
        self.label_11.setMaximumSize(QtCore.QSize(50, 15))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 4, 1, 1)
        self.bandpassHighcut_kHz_ui = QtWidgets.QLineEdit(self.layoutWidget)
        self.bandpassHighcut_kHz_ui.setMinimumSize(QtCore.QSize(60, 20))
        self.bandpassHighcut_kHz_ui.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.bandpassHighcut_kHz_ui.setFont(font)
        self.bandpassHighcut_kHz_ui.setPlaceholderText("")
        self.bandpassHighcut_kHz_ui.setObjectName("bandpassHighcut_kHz_ui")
        self.gridLayout.addWidget(self.bandpassHighcut_kHz_ui, 3, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setMinimumSize(QtCore.QSize(50, 15))
        self.label_12.setMaximumSize(QtCore.QSize(50, 15))
        self.label_12.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 6, 1, 1, QtCore.Qt.AlignRight)
        self.order_ui = QtWidgets.QLineEdit(self.layoutWidget)
        self.order_ui.setMinimumSize(QtCore.QSize(60, 20))
        self.order_ui.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.order_ui.setFont(font)
        self.order_ui.setPlaceholderText("")
        self.order_ui.setObjectName("order_ui")
        self.gridLayout.addWidget(self.order_ui, 3, 7, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 4, 0, 1, 8)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setMinimumSize(QtCore.QSize(130, 15))
        self.label_15.setMaximumSize(QtCore.QSize(130, 15))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 5, 0, 1, 1)
        self.applyDownsampling_ui = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.applyDownsampling_ui.sizePolicy().hasHeightForWidth())
        self.applyDownsampling_ui.setSizePolicy(sizePolicy)
        self.applyDownsampling_ui.setMinimumSize(QtCore.QSize(60, 20))
        self.applyDownsampling_ui.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.applyDownsampling_ui.setText("")
        self.applyDownsampling_ui.setTristate(False)
        self.applyDownsampling_ui.setObjectName("applyDownsampling_ui")
        self.gridLayout.addWidget(self.applyDownsampling_ui, 5, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setMinimumSize(QtCore.QSize(100, 0))
        self.label_14.setMaximumSize(QtCore.QSize(60, 15))
        self.label_14.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 2, 1, 2)
        self.targetFrq_kHz_ui = QtWidgets.QLineEdit(self.layoutWidget)
        self.targetFrq_kHz_ui.setMinimumSize(QtCore.QSize(60, 20))
        self.targetFrq_kHz_ui.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.targetFrq_kHz_ui.setFont(font)
        self.targetFrq_kHz_ui.setPlaceholderText("")
        self.targetFrq_kHz_ui.setObjectName("targetFrq_kHz_ui")
        self.gridLayout.addWidget(self.targetFrq_kHz_ui, 5, 4, 1, 2)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 6, 0, 1, 8)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setMinimumSize(QtCore.QSize(130, 15))
        self.label_16.setMaximumSize(QtCore.QSize(130, 15))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 7, 0, 1, 1)
        self.setHistogramLevels_ui = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.setHistogramLevels_ui.sizePolicy().hasHeightForWidth())
        self.setHistogramLevels_ui.setSizePolicy(sizePolicy)
        self.setHistogramLevels_ui.setMinimumSize(QtCore.QSize(60, 20))
        self.setHistogramLevels_ui.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.setHistogramLevels_ui.setText("")
        self.setHistogramLevels_ui.setTristate(False)
        self.setHistogramLevels_ui.setObjectName("setHistogramLevels_ui")
        self.gridLayout.addWidget(self.setHistogramLevels_ui, 7, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setMinimumSize(QtCore.QSize(30, 0))
        self.label_17.setMaximumSize(QtCore.QSize(30, 15))
        self.label_17.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 7, 2, 1, 1)
        self.histogramLevelMin_ui = QtWidgets.QLineEdit(self.layoutWidget)
        self.histogramLevelMin_ui.setMinimumSize(QtCore.QSize(60, 20))
        self.histogramLevelMin_ui.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.histogramLevelMin_ui.setFont(font)
        self.histogramLevelMin_ui.setPlaceholderText("")
        self.histogramLevelMin_ui.setObjectName("histogramLevelMin_ui")
        self.gridLayout.addWidget(self.histogramLevelMin_ui, 7, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setMinimumSize(QtCore.QSize(30, 0))
        self.label_18.setMaximumSize(QtCore.QSize(30, 15))
        self.label_18.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 7, 4, 1, 1)
        self.histogramLevelMax_ui = QtWidgets.QLineEdit(self.layoutWidget)
        self.histogramLevelMax_ui.setMinimumSize(QtCore.QSize(60, 20))
        self.histogramLevelMax_ui.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.histogramLevelMax_ui.setFont(font)
        self.histogramLevelMax_ui.setPlaceholderText("")
        self.histogramLevelMax_ui.setObjectName("histogramLevelMax_ui")
        self.gridLayout.addWidget(self.histogramLevelMax_ui, 7, 5, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 8, 0, 1, 8)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setMinimumSize(QtCore.QSize(130, 15))
        self.label_19.setMaximumSize(QtCore.QSize(130, 15))
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 9, 0, 1, 1)
        self.saveHistogramColor_ui = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.saveHistogramColor_ui.sizePolicy().hasHeightForWidth())
        self.saveHistogramColor_ui.setSizePolicy(sizePolicy)
        self.saveHistogramColor_ui.setMinimumSize(QtCore.QSize(60, 20))
        self.saveHistogramColor_ui.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.saveHistogramColor_ui.setText("")
        self.saveHistogramColor_ui.setTristate(False)
        self.saveHistogramColor_ui.setObjectName("saveHistogramColor_ui")
        self.gridLayout.addWidget(self.saveHistogramColor_ui, 9, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 10, 0, 1, 8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(50, 15))
        self.label_9.setMaximumSize(QtCore.QSize(20, 15))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 11, 0, 1, 1, QtCore.Qt.AlignRight)
        self.scaleLinLogSqrt_ui = QtWidgets.QComboBox(self.layoutWidget)
        self.scaleLinLogSqrt_ui.setMinimumSize(QtCore.QSize(60, 20))
        self.scaleLinLogSqrt_ui.setMaximumSize(QtCore.QSize(60, 20))
        self.scaleLinLogSqrt_ui.setObjectName("scaleLinLogSqrt_ui")
        self.scaleLinLogSqrt_ui.addItem("")
        self.scaleLinLogSqrt_ui.addItem("")
        self.scaleLinLogSqrt_ui.addItem("")
        self.gridLayout.addWidget(self.scaleLinLogSqrt_ui, 11, 1, 1, 1)
        self.getFromUiApplyAndClose_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.getFromUiApplyAndClose_btn.setMinimumSize(QtCore.QSize(50, 20))
        self.getFromUiApplyAndClose_btn.setMaximumSize(QtCore.QSize(50, 20))
        self.getFromUiApplyAndClose_btn.setObjectName("getFromUiApplyAndClose_btn")
        self.gridLayout.addWidget(self.getFromUiApplyAndClose_btn, 11, 5, 1, 1)
        self.saveSettings_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.saveSettings_btn.setMinimumSize(QtCore.QSize(80, 20))
        self.saveSettings_btn.setMaximumSize(QtCore.QSize(80, 20))
        self.saveSettings_btn.setObjectName("saveSettings_btn")
        self.gridLayout.addWidget(self.saveSettings_btn, 11, 6, 1, 1)
        self.resetSetings_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.resetSetings_btn.setMinimumSize(QtCore.QSize(50, 20))
        self.resetSetings_btn.setMaximumSize(QtCore.QSize(50, 20))
        self.resetSetings_btn.setObjectName("resetSetings_btn")
        self.gridLayout.addWidget(self.resetSetings_btn, 11, 7, 1, 1)
        self.fs_kHz_ui = QtWidgets.QLineEdit(self.layoutWidget)
        self.fs_kHz_ui.setMinimumSize(QtCore.QSize(60, 20))
        self.fs_kHz_ui.setMaximumSize(QtCore.QSize(60, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.fs_kHz_ui.setPalette(palette)
        self.fs_kHz_ui.setAutoFillBackground(False)
        self.fs_kHz_ui.setFrame(True)
        self.fs_kHz_ui.setObjectName("fs_kHz_ui")
        self.gridLayout.addWidget(self.fs_kHz_ui, 0, 1, 1, 1)

        self.retranslateUi(spectrogramSettingsWidget)
        QtCore.QMetaObject.connectSlotsByName(spectrogramSettingsWidget)

    def retranslateUi(self, spectrogramSettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        spectrogramSettingsWidget.setWindowTitle(_translate("spectrogramSettingsWidget", "spectrogramSettings"))
        self.label_2.setText(_translate("spectrogramSettingsWidget", "signal frq, kHz"))
        self.label.setText(_translate("spectrogramSettingsWidget", "nfft"))
        self.nfft_ui.setText(_translate("spectrogramSettingsWidget", "256"))
        self.label_4.setText(_translate("spectrogramSettingsWidget", "nperseg"))
        self.nperseg_ui.setText(_translate("spectrogramSettingsWidget", "256"))
        self.label_5.setText(_translate("spectrogramSettingsWidget", "noverlap"))
        self.noverlap_ui.setText(_translate("spectrogramSettingsWidget", "32"))
        self.label_3.setText(_translate("spectrogramSettingsWidget", "window"))
        self.window_ui.setText(_translate("spectrogramSettingsWidget", "hamming"))
        self.label_6.setText(_translate("spectrogramSettingsWidget", "detrend"))
        self.detrend_ui.setText(_translate("spectrogramSettingsWidget", "constant"))
        self.label_7.setText(_translate("spectrogramSettingsWidget", "scaling"))
        self.scaling_ui.setText(_translate("spectrogramSettingsWidget", "density"))
        self.label_8.setText(_translate("spectrogramSettingsWidget", "mode"))
        self.mode_ui.setText(_translate("spectrogramSettingsWidget", "psd"))
        self.label_13.setText(_translate("spectrogramSettingsWidget", "apply bandPass, kHz"))
        self.label_10.setText(_translate("spectrogramSettingsWidget", "lowcut"))
        self.bandpassLowcut_kHz_ui.setText(_translate("spectrogramSettingsWidget", "5000"))
        self.label_11.setText(_translate("spectrogramSettingsWidget", "highcut"))
        self.bandpassHighcut_kHz_ui.setText(_translate("spectrogramSettingsWidget", "15000"))
        self.label_12.setText(_translate("spectrogramSettingsWidget", "order"))
        self.order_ui.setText(_translate("spectrogramSettingsWidget", "3"))
        self.label_15.setText(_translate("spectrogramSettingsWidget", "apply downsampling"))
        self.label_14.setText(_translate("spectrogramSettingsWidget", "target frq, kHz"))
        self.targetFrq_kHz_ui.setText(_translate("spectrogramSettingsWidget", "500"))
        self.label_16.setText(_translate("spectrogramSettingsWidget", "set histogram levels"))
        self.label_17.setText(_translate("spectrogramSettingsWidget", "min"))
        self.histogramLevelMin_ui.setToolTip(_translate("spectrogramSettingsWidget", "*SxxMax"))
        self.histogramLevelMin_ui.setText(_translate("spectrogramSettingsWidget", "0.1"))
        self.label_18.setText(_translate("spectrogramSettingsWidget", "max"))
        self.histogramLevelMax_ui.setToolTip(_translate("spectrogramSettingsWidget", "*SxxMax"))
        self.histogramLevelMax_ui.setText(_translate("spectrogramSettingsWidget", "1"))
        self.label_19.setText(_translate("spectrogramSettingsWidget", "save histogram color"))
        self.label_9.setText(_translate("spectrogramSettingsWidget", "type"))
        self.scaleLinLogSqrt_ui.setItemText(0, _translate("spectrogramSettingsWidget", "linear"))
        self.scaleLinLogSqrt_ui.setItemText(1, _translate("spectrogramSettingsWidget", "log10"))
        self.scaleLinLogSqrt_ui.setItemText(2, _translate("spectrogramSettingsWidget", "sqrt"))
        self.getFromUiApplyAndClose_btn.setText(_translate("spectrogramSettingsWidget", "ok"))
        self.saveSettings_btn.setText(_translate("spectrogramSettingsWidget", "save to file"))
        self.resetSetings_btn.setText(_translate("spectrogramSettingsWidget", "reset"))
        self.fs_kHz_ui.setText(_translate("spectrogramSettingsWidget", "50"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    spectrogramSettingsWidget = QtWidgets.QWidget()
    ui = Ui_spectrogramSettingsWidget()
    ui.setupUi(spectrogramSettingsWidget)
    spectrogramSettingsWidget.show()
    sys.exit(app.exec_())

